# Generated by Django 4.0.4 on 2022-04-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='titile',
            new_name='title',
        ),
    ]
