# Generated by Django 4.0.4 on 2022-04-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_rename_titile_bookmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='pages',
            field=models.IntegerField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='format xxx.xx', max_digits=5),
        ),
    ]
